return {
    {'nvim-treesitter/nvim-treesitter'},
    { 'junegunn/vim-easy-align' },
    { 'junegunn/fzf' },
    { 'junegunn/fzf.vim' },
    { 'liuchengxu/eleline.vim' },
    { 'bling/vim-airline' },
    { 'fatih/vim-go' },
    { 'lervag/vimtex' },
    {
        'iamcco/markdown-preview.nvim',
        ft = "norg",
        -- TODO: Figure out install?
        -- opts = { 'do': ':call mkdp#util#install()', 'for': 'markdown' }
    },
    { 'tpope/vim-surround' },
    { 'tpope/vim-repeat' },
    { 'pangloss/vim-javascript' },
    { 'leafgarland/typescript-vim' },
    { 'othree/yajs.vim' },
    { 'jparise/vim-graphql' },
    { 'moll/vim-node' },
    { 'prisma/vim-prisma' },
    { 'HerringtonDarkholme/yats.vim' },
    { 'scrooloose/nerdtree' },
    { 'liuchengxu/vista.vim' },
    { 'raimondi/delimitmate' },
    { 'tpope/vim-commentary' },
    { 'romainl/vim-qf' },
    { 'mbbill/undotree' },
    { 'hashivim/vim-terraform' },
}
